### ISSUE TITLE
ID Site Register Not Working

### ISSUE THREAD

**Issue by bretterer** [stormpath/stormpath-sdk-php#46]
The JWT for the Register page is being created but when you get there and type in a password, You receive the following in the console. 

```
TypeError: Cannot read property 'minLength' of null
    at Array.link.b.validate.e (https://xxx.id.stormpath.io/scripts/app.js:1:8939)
    at k.link.b.validate (https://xxx.id.stormpath.io/scripts/app.js:1:9502)
    at Object.a.fields.(anonymous function).validate (https://xxx.id.stormpath.io/scripts/app.js:1:7035)
    at https://xxx.id.stormpath.io/scripts/app.js:1:5971
    at Array.filter (native)
    at k.a.submit (https://xxx.id.stormpath.io/scripts/app.js:1:5925)
    at ee.functionCall (https://xxx.id.stormpath.io/scripts/vendor.js:6:13813)
    at https://xxx.id.stormpath.io/scripts/vendor.js:6:20990
    at k.$get.k.$eval (https://xxx.id.stormpath.io/scripts/vendor.js:5:11080)
    at k.$get.k.$apply (https://xxx.id.stormpath.io/scripts/vendor.js:5:11358)
```

This is causing the ability to register to not work.

**Comment by bretterer** [comment]
Here are some screenshots of my application.

![image](https://cloud.githubusercontent.com/assets/1906920/7617851/f0487c26-f97b-11e4-9d41-fe71c81e3315.png)

![image](https://cloud.githubusercontent.com/assets/1906920/7617863/fe15ea14-f97b-11e4-9452-dd29ab3ff7e2.png)

![image](https://cloud.githubusercontent.com/assets/1906920/7617869/07bd721c-f97c-11e4-993d-507b16e72b0e.png)

**Comment by bretterer** [comment]
Seems this is fixed now.
